use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'LZSwiftAppDelegateKit_Example' do
  pod 'LZSwiftAppDelegateKit', :path => '../'
  pod 'URLNavigator', '2.3.0'
  pod 'LZSwiftDelegate', '0.0.2'


  target 'LZSwiftAppDelegateKit_Tests' do
    inherit! :search_paths
  end
  
end
